### ISSUE TITLE
AttributeError: 'int' object has no attribute 'id'

### ISSUE THREAD

**Issue by springjools** [adafruit/Adafruit_CircuitPython_HCSR04#12]
pi@getabock:~ $ python3 range_sensor.py
__main__    : INFO     Measuring distance with pins trig=2,echo=3
Traceback (most recent call last):
  File "range_sensor.py", line 18, in <module>
    with HCSR04(TRIG, ECHO) as sonar:
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_hcsr04.py", line 98, in __init__
    self._trig = DigitalInOut(trigger_pin)
  File "/home/pi/.local/lib/python3.7/site-packages/digitalio.py", line 76, in __init__
    self._pin = Pin(pin.id)
AttributeError: 'int' object has no attribute 'id'

**Comment by ladyada** [comment]
hi please try running the example in this library - you can use that to initialize/crib the sensor functionality, you're probably not passing in valid pins :)
